
clusterName: asavu-zookeeper
clusterSize: 3

# AWS Credentials 
whirr:
  identity: identity
  credential: credential

logging:
  level: INFO
  console:
    enabled: true
    threshold: INFO
  loggers:
    jclouds.ssh: ERROR
    net.schmizz.sshj: ERROR

